nome = input('Digite algo: ')
print(f'O tipo primitivo dessa string é: {type(nome)}')
print(f'Só tem espaços?', 'Sim.' if nome.isspace() else 'Não')
print(f'É um número?', 'Sim' if nome.isnumeric() else 'Não')
print(f'É alfabético?', 'Sim' if nome.isalpha() else 'Não')
print(f'É alfanumérico?', 'Sim' if nome.isalnum() else 'Não')
print(f'Está em maiúsculas?', 'Sim' if nome.isupper() else 'Não')
print(f'Está em minúsculas?', 'Sim' if nome.islower() else 'Não')
print(f'Está captalizada?', 'Sim' if nome.istitle() else 'Não')
